<?php

namespace IFZ\TowerOfDimensionsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MercenaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MercenaryRepository extends EntityRepository
{
	
}