<?php

namespace IFZ\TowerOfDimensionsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SteamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SteamRepository extends EntityRepository
{
	public function findBySteamId($id)
	{
		$result = $this->getEntityManager()
            ->createQuery("SELECT p FROM IFZTowerofDimensionsBundle:Steam p WHERE p.steamId = :steamId")
            ->setParameter('steamId', $id)
            ->getResult();

        if(!$result)
        	return $result;
        else
        	return $result[0];
	}
}