security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    factories:
        - %kernel.root_dir%/../vendor/bundles/Fp/OpenIdBundle/Resources/config/security_factories.xml

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: kitten, roles: 'ROLE_ADMIN' }

    firewalls:
        main:
            pattern: ^/

            fp_openid: ~
                #failure_path: /finish_login_openid
                #provider: openid_user_manager
                #required_attributes:
                 #   -                                     contact/email
                  #  -                                     namePerson/first
                   # -                                     namePerson/last

            logout:       true
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
   # providers:
    #    openid_user_manager:
     #       id:                                           fp_openid.user_manager

    access_control:
        - { path: ^/finish_login_openid$, role: IS_AUTHENTICATED_ANONYMOUSLY }

    access_control:
        - { path: ^/login_openid$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured_area, role: IS_AUTHENTICATED_OPENID }
