IFZTowerofDimensionsBundle_mercenaries:
    pattern:  /mercenaries/
    defaults: { _controller: IFZTowerofDimensionsBundle:Default:mercenaries }
IFZTowerofDimensionsBundle_homepage:
    pattern:  /
    defaults: { _controller: IFZTowerofDimensionsBundle:Default:index }
