tod_login:
    pattern:  /{steam}/ 
    defaults:  { _controller: ifztowerofdimensionsBundle:Login:init, steam: 'empty' }
tod_mainStart:
    pattern:  /
    defaults:  { _controller: ifztowerofdimensionsBundle:Login:init, steam: 'empty' }