IFZTowerofDimensionsBundle_mercenariesDetail:
    pattern:  /mercenaries/detail/{id}/
    defaults: { _controller: IFZTowerofDimensionsBundle:Mercenaries:mercenariesDetail, id: "empty" }
IFZTowerofDimensionsBundle_mercenaries:
    pattern:  /mercenaries/
    defaults: { _controller: IFZTowerofDimensionsBundle:Mercenaries:mercenaries }
IFZTowerofDimensionsBundle_homepage:
    pattern:  /
    defaults: { _controller: IFZTowerofDimensionsBundle:Default:index }