<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class IFZTowerofDimensionsBundleEntityMercenaryProxy extends \IFZ\TowerofDimensionsBundle\Entity\Mercenary implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setIdBase($idBase)
    {
        $this->__load();
        return parent::setIdBase($idBase);
    }

    public function getIdBase()
    {
        $this->__load();
        return parent::getIdBase();
    }

    public function setNivel($nivel)
    {
        $this->__load();
        return parent::setNivel($nivel);
    }

    public function getNivel()
    {
        $this->__load();
        return parent::getNivel();
    }

    public function setExp($exp)
    {
        $this->__load();
        return parent::setExp($exp);
    }

    public function getExp()
    {
        $this->__load();
        return parent::getExp();
    }

    public function setAgilidad($agilidad)
    {
        $this->__load();
        return parent::setAgilidad($agilidad);
    }

    public function getAgilidad()
    {
        $this->__load();
        return parent::getAgilidad();
    }

    public function setDestreza($destreza)
    {
        $this->__load();
        return parent::setDestreza($destreza);
    }

    public function getDestreza()
    {
        $this->__load();
        return parent::getDestreza();
    }

    public function setConstitucion($constitucion)
    {
        $this->__load();
        return parent::setConstitucion($constitucion);
    }

    public function getConstitucion()
    {
        $this->__load();
        return parent::getConstitucion();
    }

    public function setFuerza($fuerza)
    {
        $this->__load();
        return parent::setFuerza($fuerza);
    }

    public function getFuerza()
    {
        $this->__load();
        return parent::getFuerza();
    }

    public function setInteligencia($inteligencia)
    {
        $this->__load();
        return parent::setInteligencia($inteligencia);
    }

    public function getInteligencia()
    {
        $this->__load();
        return parent::getInteligencia();
    }

    public function setSabiduria($sabiduria)
    {
        $this->__load();
        return parent::setSabiduria($sabiduria);
    }

    public function getSabiduria()
    {
        $this->__load();
        return parent::getSabiduria();
    }

    public function setCarisma($carisma)
    {
        $this->__load();
        return parent::setCarisma($carisma);
    }

    public function getCarisma()
    {
        $this->__load();
        return parent::getCarisma();
    }

    public function setPoder($poder)
    {
        $this->__load();
        return parent::setPoder($poder);
    }

    public function getPoder()
    {
        $this->__load();
        return parent::getPoder();
    }

    public function setMarcial($marcial)
    {
        $this->__load();
        return parent::setMarcial($marcial);
    }

    public function getMarcial()
    {
        $this->__load();
        return parent::getMarcial();
    }

    public function setStealth($stealth)
    {
        $this->__load();
        return parent::setStealth($stealth);
    }

    public function getStealth()
    {
        $this->__load();
        return parent::getStealth();
    }

    public function setMagia($magia)
    {
        $this->__load();
        return parent::setMagia($magia);
    }

    public function getMagia()
    {
        $this->__load();
        return parent::getMagia();
    }

    public function setTecnologia($tecnologia)
    {
        $this->__load();
        return parent::setTecnologia($tecnologia);
    }

    public function getTecnologia()
    {
        $this->__load();
        return parent::getTecnologia();
    }

    public function setCrecimientoAgilidad($crecimientoAgilidad)
    {
        $this->__load();
        return parent::setCrecimientoAgilidad($crecimientoAgilidad);
    }

    public function getCrecimientoAgilidad()
    {
        $this->__load();
        return parent::getCrecimientoAgilidad();
    }

    public function setCrecimientoDestreza($crecimientoDestreza)
    {
        $this->__load();
        return parent::setCrecimientoDestreza($crecimientoDestreza);
    }

    public function getCrecimientoDestreza()
    {
        $this->__load();
        return parent::getCrecimientoDestreza();
    }

    public function setCrecimientoConstitucion($crecimientoConstitucion)
    {
        $this->__load();
        return parent::setCrecimientoConstitucion($crecimientoConstitucion);
    }

    public function getCrecimientoConstitucion()
    {
        $this->__load();
        return parent::getCrecimientoConstitucion();
    }

    public function setCrecimientoFuerza($crecimientoFuerza)
    {
        $this->__load();
        return parent::setCrecimientoFuerza($crecimientoFuerza);
    }

    public function getCrecimientoFuerza()
    {
        $this->__load();
        return parent::getCrecimientoFuerza();
    }

    public function setCrecimientoInteligencia($crecimientoInteligencia)
    {
        $this->__load();
        return parent::setCrecimientoInteligencia($crecimientoInteligencia);
    }

    public function getCrecimientoInteligencia()
    {
        $this->__load();
        return parent::getCrecimientoInteligencia();
    }

    public function setCrecimientoSabiduria($crecimientoSabiduria)
    {
        $this->__load();
        return parent::setCrecimientoSabiduria($crecimientoSabiduria);
    }

    public function getCrecimientoSabiduria()
    {
        $this->__load();
        return parent::getCrecimientoSabiduria();
    }

    public function setCrecimientoCarisma($crecimientoCarisma)
    {
        $this->__load();
        return parent::setCrecimientoCarisma($crecimientoCarisma);
    }

    public function getCrecimientoCarisma()
    {
        $this->__load();
        return parent::getCrecimientoCarisma();
    }

    public function setCrecimientoPoder($crecimientoPoder)
    {
        $this->__load();
        return parent::setCrecimientoPoder($crecimientoPoder);
    }

    public function getCrecimientoPoder()
    {
        $this->__load();
        return parent::getCrecimientoPoder();
    }

    public function setCrecimientoMarcial($crecimientoMarcial)
    {
        $this->__load();
        return parent::setCrecimientoMarcial($crecimientoMarcial);
    }

    public function getCrecimientoMarcial()
    {
        $this->__load();
        return parent::getCrecimientoMarcial();
    }

    public function setCrecimientoStealth($crecimientoStealth)
    {
        $this->__load();
        return parent::setCrecimientoStealth($crecimientoStealth);
    }

    public function getCrecimientoStealth()
    {
        $this->__load();
        return parent::getCrecimientoStealth();
    }

    public function setCrecimientoMagia($crecimientoMagia)
    {
        $this->__load();
        return parent::setCrecimientoMagia($crecimientoMagia);
    }

    public function getCrecimientoMagia()
    {
        $this->__load();
        return parent::getCrecimientoMagia();
    }

    public function setCrecimientoTecnologia($crecimientoTecnologia)
    {
        $this->__load();
        return parent::setCrecimientoTecnologia($crecimientoTecnologia);
    }

    public function getCrecimientoTecnologia()
    {
        $this->__load();
        return parent::getCrecimientoTecnologia();
    }

    public function setHpCalculo($hpCalculo)
    {
        $this->__load();
        return parent::setHpCalculo($hpCalculo);
    }

    public function getHpCalculo()
    {
        $this->__load();
        return parent::getHpCalculo();
    }

    public function setItem1($item1)
    {
        $this->__load();
        return parent::setItem1($item1);
    }

    public function getItem1()
    {
        $this->__load();
        return parent::getItem1();
    }

    public function setItem2($item2)
    {
        $this->__load();
        return parent::setItem2($item2);
    }

    public function getItem2()
    {
        $this->__load();
        return parent::getItem2();
    }

    public function setItem3($item3)
    {
        $this->__load();
        return parent::setItem3($item3);
    }

    public function getItem3()
    {
        $this->__load();
        return parent::getItem3();
    }

    public function setItem4($item4)
    {
        $this->__load();
        return parent::setItem4($item4);
    }

    public function getItem4()
    {
        $this->__load();
        return parent::getItem4();
    }

    public function setItem5($item5)
    {
        $this->__load();
        return parent::setItem5($item5);
    }

    public function getItem5()
    {
        $this->__load();
        return parent::getItem5();
    }

    public function setItem6($item6)
    {
        $this->__load();
        return parent::setItem6($item6);
    }

    public function getItem6()
    {
        $this->__load();
        return parent::getItem6();
    }

    public function setHpMax($hpMax)
    {
        $this->__load();
        return parent::setHpMax($hpMax);
    }

    public function getHpMax()
    {
        $this->__load();
        return parent::getHpMax();
    }

    public function setHpActual($hpActual)
    {
        $this->__load();
        return parent::setHpActual($hpActual);
    }

    public function getHpActual()
    {
        $this->__load();
        return parent::getHpActual();
    }

    public function setMisionActual($misionActual)
    {
        $this->__load();
        return parent::setMisionActual($misionActual);
    }

    public function getMisionActual()
    {
        $this->__load();
        return parent::getMisionActual();
    }

    public function setPlayer(\IFZ\TowerofDimensionsBundle\Entity\Player $player)
    {
        $this->__load();
        return parent::setPlayer($player);
    }

    public function getPlayer()
    {
        $this->__load();
        return parent::getPlayer();
    }

    public function readFromJson($id)
    {
        $this->__load();
        return parent::readFromJson($id);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'player', 'name', 'idBase', 'nivel', 'exp', 'agilidad', 'destreza', 'constitucion', 'fuerza', 'inteligencia', 'sabiduria', 'carisma', 'poder', 'marcial', 'stealth', 'magia', 'tecnologia', 'crecimientoAgilidad', 'crecimientoDestreza', 'crecimientoConstitucion', 'crecimientoFuerza', 'crecimientoInteligencia', 'crecimientoSabiduria', 'crecimientoCarisma', 'crecimientoPoder', 'crecimientoMarcial', 'crecimientoStealth', 'crecimientoMagia', 'crecimientoTecnologia', 'hpCalculo', 'item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'hpMax', 'hpActual', 'misionActual');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}